name: Deploy to ECS

on:
  workflow_call:
    inputs:
      commit:
        type: string
        description: 'Full SHA of commit to be deployed'
        required: false
      appenv:
        type: string
        description: 'Environment to be deployed on'
        required: true

jobs:
  deploy-to-ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commit }}
          fetch-depth: 0

      - name: Set short_sha
        id: vars
        run: |
          if [[ "${{ inputs.commit }}" == "" ]]; then
            echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          else
            echo "short_sha=$(git rev-parse --short ${{ inputs.commit }})" >> $GITHUB_ENV
          fi

      - name: echo
        run: |
          echo "Commit to deploy: ${{ env.short_sha }}"
      
      - name: cat file
        run: |
          cat test.txt